//
//  Data.swift
//  Pquotes
//
//  Created by Yaseen Dar on 29/03/18.
//  Copyright © 2018 Yaseen Dar. All rights reserved.
//

import Foundation

let authors = ["Ada Lovelace", "Addy Osmani", "Alan Kay", "Alan Perlis", "Alan Turing", "Albert Einstein", "Anders Hejlsberg", "Andy Hertzfeld", "Andy Hunt (author)", "Anonymous", "Arthur C. Clarke", "Bdale Garbee", "Bill Gates", "Bjarne Stroustrup", "Bob Carr", "Bob Frankston", "Brian Cantwell Smith", "Brian Kernighan", "Buckminster Fuller", "Butler Lampson", "Carl Friedrich Gauss", "Charles Babbage", "Charles Simonyi", "Chris Sacca", "Chris Wenham", "Damian Conway", "Dan Bricklin", "Daniel T. Barry", "Danny Hillis", "David Gelernter", "David Leinweber", "David Parnas", "David Wheeler (computer scientist)", "Dennis Ritchie", "Don Norman", "Donald Knuth", "Doug Linder", "Douglas Crockford", "Edsger W. Dijkstra", "Edward V. Berard", "Ellen Ullman", "Elon Musk", "Eric S. Raymond", "Filipe Fortes", "Fred Brooks", "Friedrich Bauer", "Gary Kildall", "George Boole", "George Carrette", "Gerald Weinberg", "Gordon Bell", "Gottfried Wilhelm Leibniz", "Grace Hopper", "Grady Booch", "Hal Abelson", "Harlan Mills", "Henry Ford", "Henry Petroski", "Ivan Sutherland", "James Gleick", "Jamie Zawinski", "Jan L. A. van de Snepscheut", "Jaron Lanier", "Jef Raskin", "Jeff Hammerbacher", "Jeff Sickel", "Jeremy S. Anderson", "Jim Coplien", "Jim Horning", "Joe Armstrong (programmer)", "Joel Spolsky", "John Carmack", "John Gall (author)", "John Johnson", "John Locke", "John McCarthy (computer scientist)", "John Ousterhout", "John Romero", "John Warnock", "John von Neumann", "Jonathan Sachs", "Jonathan Shewchuk", "Joseph Yoder (computer scientist)", "Joshua Bloch", "Ken Olsen", "Ken Thompson", "Kent Beck", "Kevlin Henney", "L. Peter Deutsch", "Laurence J. Peter", "Lawrence Flon", "Leslie Lamport", "Linus Torvalds", "Luciano Ramalho", "Ludwig Wittgenstein", "Manny Lehman (computer scientist)", "Manuel Blum", "Marijn Haverbeke", "Mario Fusco", "Mark Gibbs", "Martin Fowler", "Marvin Minsky", "Maurice Wilkes", "Michael A. Jackson", "Michael Hawley", "Michael Stal", "Nathaniel Borenstein", "Niklaus Wirth", "P. J. Plauger", "Pamela Zave", "Paul Graham (programmer)", "Pete Cordell", "Peter Roizen", "Philip Greenspun", "Poul Anderson", "Poul-Henning Kamp", "Quarry worker's creed", "Ralph Johnson (computer scientist)", "Randall E. Stross", "Ray Ozzie", "Rene Descartes", "Rich Skrenta", "Richard E. Pattis", "Richard Feynman", "Richard Hamming", "Richard Moore (engineer)", "Richard P. Gabriel", "Richard Stallman", "Rick Osborne", "Rob Pike", "Robert C. Martin", "Robert L. Glass", "Ron Jeffries", "Roy Fielding", "Ryan Singer", "Sean Parent", "Seymour Cray", "Simon Peyton Jones", "Sophocles", "Stan Kelly-Bootle", "Steve Jobs", "Steve McConnell", "Steve Wozniak", "Stewart Brand", "Ted Nelson", "Terry Winograd", "Thomas J. Watson", "Tim Berners-Lee", "Tom Cargill", "Tom DeMarco", "Tony Hoare", "Tony Parisi (software developer)", "Toru Iwatani", "Vannevar Bush", "Vint Cerf", "Ward Cunningham", "Wayne Ratliff", "William Wulf"]

